"""Added legal_description to table

Revision ID: 6eee5564b28d
Revises: 83f704edef57
Create Date: 2025-10-05 19:21:28.622421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eee5564b28d'
down_revision: Union[str, None] = '83f704edef57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('legal_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'legal_description')
    # ### end Alembic commands ###
