"""Added favorite_properties to users

Revision ID: 782fb65c25e8
Revises: e221e40ce4b9
Create Date: 2025-11-23 17:44:33.103348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '782fb65c25e8'
down_revision: Union[str, None] = 'e221e40ce4b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_properties', postgresql.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_properties')
    # ### end Alembic commands ###
