"""Added nullable to favorite_properties

Revision ID: c5dfddcc01e5
Revises: 782fb65c25e8
Create Date: 2025-11-23 17:46:28.587811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5dfddcc01e5'
down_revision: Union[str, None] = '782fb65c25e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
