"""add composite unique constraints and indexes

Revision ID: e1bf2edb6f66
Revises: 6eee5564b28d
Create Date: 2025-10-05 19:50:41.885310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1bf2edb6f66'
down_revision: Union[str, None] = '6eee5564b28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_properties_assessor_id'), 'properties', ['assessor_id'], unique=False)
    op.create_index(op.f('ix_properties_bedrooms'), 'properties', ['bedrooms'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_formatted_address'), 'properties', ['formatted_address'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_state'), 'properties', ['state'], unique=False)
    op.create_unique_constraint('unique_assessor_id', 'properties', ['assessor_id'])
    op.create_unique_constraint('unique_full_address', 'properties', ['formatted_address', 'address_line1', 'address_line2', 'city', 'state', 'zip_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_full_address', 'properties', type_='unique')
    op.drop_constraint('unique_assessor_id', 'properties', type_='unique')
    op.drop_index(op.f('ix_properties_state'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_formatted_address'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index(op.f('ix_properties_bedrooms'), table_name='properties')
    op.drop_index(op.f('ix_properties_assessor_id'), table_name='properties')
    # ### end Alembic commands ###
