"""Updated firebase_uid to firebase_id

Revision ID: e221e40ce4b9
Revises: e1bf2edb6f66
Create Date: 2025-11-05 11:27:16.972733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e221e40ce4b9'
down_revision: Union[str, None] = 'e1bf2edb6f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.create_index(op.f('ix_users_firebase_id'), 'users', ['firebase_id'], unique=True)
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_firebase_id'), table_name='users')
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.drop_column('users', 'firebase_id')
    # ### end Alembic commands ###
